package org.cloudburstmc.protocol.bedrock.codec.v291;

import org.cloudburstmc.protocol.bedrock.data.world.event.ParticleType;

import org.cloudburstmc.protocol.bedrock.data.world.event.LevelEventType;
import org.cloudburstmc.protocol.bedrock.data.world.event.LevelEvent;

import org.cloudburstmc.protocol.bedrock.data.sound.LevelSoundEvent;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.cloudburstmc.protocol.bedrock.codec.BedrockCodec;
import org.cloudburstmc.protocol.bedrock.codec.ActorDataTypeMap;
import org.cloudburstmc.protocol.bedrock.codec.v291.serializer.*;
import org.cloudburstmc.protocol.bedrock.data.PacketRecipient;
import org.cloudburstmc.protocol.bedrock.data.actor.ActorEvent;
import org.cloudburstmc.protocol.bedrock.data.command.CommandParam;
import org.cloudburstmc.protocol.bedrock.data.actor.ActorDataFormat;
import org.cloudburstmc.protocol.bedrock.data.actor.ActorDataTypes;
import org.cloudburstmc.protocol.bedrock.data.actor.ActorFlags;
import org.cloudburstmc.protocol.bedrock.packet.*;
import org.cloudburstmc.protocol.bedrock.transformer.*;
import org.cloudburstmc.protocol.common.util.TypeMap;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Bedrock_v291 {

    protected static final TypeMap<ActorFlags> ENTITY_FLAGS = TypeMap.builder(ActorFlags.class)
            .insert(0, ActorFlags.ON_FIRE)
            .insert(1, ActorFlags.SNEAKING)
            .insert(2, ActorFlags.RIDING)
            .insert(3, ActorFlags.SPRINTING)
            .insert(4, ActorFlags.USING_ITEM)
            .insert(5, ActorFlags.INVISIBLE)
            .insert(6, ActorFlags.TEMPTED)
            .insert(7, ActorFlags.IN_LOVE)
            .insert(8, ActorFlags.SADDLED)
            .insert(9, ActorFlags.POWERED)
            .insert(10, ActorFlags.IGNITED)
            .insert(11, ActorFlags.BABY)
            .insert(12, ActorFlags.CONVERTING)
            .insert(13, ActorFlags.CRITICAL)
            .insert(14, ActorFlags.CAN_SHOW_NAME)
            .insert(15, ActorFlags.ALWAYS_SHOW_NAME)
            .insert(16, ActorFlags.NO_AI)
            .insert(17, ActorFlags.SILENT)
            .insert(18, ActorFlags.WALL_CLIMBING)
            .insert(19, ActorFlags.CAN_CLIMB)
            .insert(20, ActorFlags.CAN_SWIM)
            .insert(21, ActorFlags.CAN_FLY)
            .insert(22, ActorFlags.CAN_WALK)
            .insert(23, ActorFlags.RESTING)
            .insert(24, ActorFlags.SITTING)
            .insert(25, ActorFlags.ANGRY)
            .insert(26, ActorFlags.INTERESTED)
            .insert(27, ActorFlags.CHARGED)
            .insert(28, ActorFlags.TAMED)
            .insert(29, ActorFlags.ORPHANED)
            .insert(30, ActorFlags.LEASHED)
            .insert(31, ActorFlags.SHEARED)
            .insert(32, ActorFlags.GLIDING)
            .insert(33, ActorFlags.ELDER)
            .insert(34, ActorFlags.MOVING)
            .insert(35, ActorFlags.BREATHING)
            .insert(36, ActorFlags.CHESTED)
            .insert(37, ActorFlags.STACKABLE)
            .insert(38, ActorFlags.SHOW_BOTTOM)
            .insert(39, ActorFlags.STANDING)
            .insert(40, ActorFlags.SHAKING)
            .insert(41, ActorFlags.IDLING)
            .insert(42, ActorFlags.CASTING)
            .insert(43, ActorFlags.CHARGING)
            .insert(44, ActorFlags.WASD_CONTROLLED)
            .insert(45, ActorFlags.CAN_POWER_JUMP)
            .insert(46, ActorFlags.LINGERING)
            .insert(47, ActorFlags.HAS_COLLISION)
            .insert(48, ActorFlags.HAS_GRAVITY)
            .insert(49, ActorFlags.FIRE_IMMUNE)
            .insert(50, ActorFlags.DANCING)
            .insert(51, ActorFlags.ENCHANTED)
            .insert(52, ActorFlags.RETURN_TRIDENT)
            .insert(53, ActorFlags.CONTAINER_IS_PRIVATE)
            .insert(54, ActorFlags.IS_TRANSFORMING)
            .insert(55, ActorFlags.DAMAGE_NEARBY_MOBS)
            .insert(56, ActorFlags.SWIMMING)
            .insert(57, ActorFlags.BRIBED)
            .insert(58, ActorFlags.IS_PREGNANT)
            .insert(59, ActorFlags.LAYING_EGG)
            .insert(60, ActorFlags.RIDER_CAN_PICK)
            .build();

    protected static final TypeMap<ParticleType> PARTICLE_TYPES = TypeMap.builder(ParticleType.class)
            .insert(0, ParticleType.UNDEFINED)
            .insert(1, ParticleType.BUBBLE)
            .insert(2, ParticleType.CRIT)
            .insert(3, ParticleType.BLOCK_FORCE_FIELD)
            .insert(4, ParticleType.SMOKE)
            .insert(5, ParticleType.EXPLODE)
            .insert(6, ParticleType.EVAPORATION)
            .insert(7, ParticleType.FLAME)
            .insert(8, ParticleType.LAVA)
            .insert(9, ParticleType.LARGE_SMOKE)
            .insert(10, ParticleType.RED_DUST)
            .insert(11, ParticleType.RISING_BORDER_DUST)
            .insert(12, ParticleType.ICON_CRACK)
            .insert(13, ParticleType.SNOWBALL_POOF)
            .insert(14, ParticleType.LARGE_EXPLODE)
            .insert(15, ParticleType.HUGE_EXPLOSION)
            .insert(16, ParticleType.MOB_FLAME)
            .insert(17, ParticleType.HEART)
            .insert(18, ParticleType.TERRAIN)
            .insert(19, ParticleType.TOWN_AURA)
            .insert(20, ParticleType.PORTAL)
            .insert(21, ParticleType.WATER_SPLASH)
            .insert(22, ParticleType.WATER_WAKE)
            .insert(23, ParticleType.DRIP_WATER)
            .insert(24, ParticleType.DRIP_LAVA)
            .insert(25, ParticleType.FALLING_DUST)
            .insert(26, ParticleType.MOB_SPELL)
            .insert(27, ParticleType.MOB_SPELL_AMBIENT)
            .insert(28, ParticleType.MOB_SPELL_INSTANTANEOUS)
            .insert(29, ParticleType.INK)
            .insert(30, ParticleType.SLIME)
            .insert(31, ParticleType.RAIN_SPLASH)
            .insert(32, ParticleType.VILLAGER_ANGRY)
            .insert(33, ParticleType.VILLAGER_HAPPY)
            .insert(34, ParticleType.ENCHANTING_TABLE)
            .insert(35, ParticleType.TRACKER_EMITTER)
            .insert(36, ParticleType.NOTE)
            .insert(37, ParticleType.WITCH_SPELL)
            .insert(38, ParticleType.CARROT_BOOST)
            .insert(39, ParticleType.MOB_APPEARANCE)
            .insert(40, ParticleType.END_ROD)
            .insert(41, ParticleType.DRAGON_BREATH)
            .insert(42, ParticleType.SPIT)
            .insert(43, ParticleType.TOTEM)
            .insert(44, ParticleType.FOOD)
            .build();

    protected static final ActorDataTypeMap ENTITY_DATA = ActorDataTypeMap.builder()
            .insert(ActorDataTypes.FLAGS, 0, ActorDataFormat.LONG, new FlagTransformer(ENTITY_FLAGS, 0))
            .insert(ActorDataTypes.STRUCTURAL_INTEGRITY, 1, ActorDataFormat.INT)
            .insert(ActorDataTypes.VARIANT, 2, ActorDataFormat.INT)
            .insert(ActorDataTypes.BLOCK, 2, ActorDataFormat.INT, new BlockDefinitionTransformer())
            .insert(ActorDataTypes.COLOR, 3, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.NAME, 4, ActorDataFormat.STRING, StringTransformer.INSTANCE)
            .insert(ActorDataTypes.OWNER_EID, 5, ActorDataFormat.LONG)
            .insert(ActorDataTypes.TARGET_EID, 6, ActorDataFormat.LONG)
            .insert(ActorDataTypes.AIR_SUPPLY, 7, ActorDataFormat.SHORT)
            .insert(ActorDataTypes.EFFECT_COLOR, 8, ActorDataFormat.INT)
            .insert(ActorDataTypes.EFFECT_AMBIENCE, 9, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.JUMP_DURATION, 10, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.HURT_TICKS, 11, ActorDataFormat.INT)
            .insert(ActorDataTypes.HURT_DIRECTION, 12, ActorDataFormat.INT)
            .insert(ActorDataTypes.ROW_TIME_LEFT, 13, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.ROW_TIME_RIGHT, 14, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.VALUE, 15, ActorDataFormat.INT)
            .insert(ActorDataTypes.DISPLAY_BLOCK_STATE, 16, ActorDataFormat.INT, new BlockDefinitionTransformer())
            .insert(ActorDataTypes.DISPLAY_FIREWORK, 16, ActorDataFormat.NBT)
            .insert(ActorDataTypes.HORSE_FLAGS, 16, ActorDataFormat.INT)
            .insert(ActorDataTypes.WITHER_SKULL_DANGEROUS, 16, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.DISPLAY_OFFSET, 17, ActorDataFormat.INT)
            .insert(ActorDataTypes.CUSTOM_DISPLAY, 18, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.HORSE_TYPE, 19, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.OLD_SWELL, 20, ActorDataFormat.INT)
            .insert(ActorDataTypes.SWELL_DIRECTION, 21, ActorDataFormat.INT)
            .insert(ActorDataTypes.CHARGE_AMOUNT, 22, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.CARRY_BLOCK_STATE, 23, ActorDataFormat.INT, new BlockDefinitionTransformer())
            .insert(ActorDataTypes.CLIENT_EVENT, 24, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.USING_ITEM, 25, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.PLAYER_FLAGS, 26, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.PLAYER_INDEX, 27, ActorDataFormat.INT)
            .insert(ActorDataTypes.BED_POSITION, 28, ActorDataFormat.VECTOR3I)
            .insert(ActorDataTypes.FIREBALL_POWER_X, 29, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.FIREBALL_POWER_Y, 30, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.FIREBALL_POWER_Z, 31, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.AUX_POWER, 32, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.FISH_X, 33, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.FISH_Z, 34, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.FISH_ANGLE, 35, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.AUX_VALUE_DATA, 36, ActorDataFormat.SHORT)
            .insert(ActorDataTypes.LEASH_HOLDER, 37, ActorDataFormat.LONG)
            .insert(ActorDataTypes.SCALE, 38, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.INTERACT_TEXT, 39, ActorDataFormat.STRING, StringTransformer.INSTANCE)
            .insert(ActorDataTypes.SKIN_ID, 40, ActorDataFormat.INT)
            .insert(ActorDataTypes.ACTIONS, 41, ActorDataFormat.STRING)
            .insert(ActorDataTypes.AIR_SUPPLY_MAX, 42, ActorDataFormat.SHORT)
            .insert(ActorDataTypes.MARK_VARIANT, 43, ActorDataFormat.INT)
            .insert(ActorDataTypes.CONTAINER_TYPE, 44, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.CONTAINER_SIZE, 45, ActorDataFormat.INT)
            .insert(ActorDataTypes.CONTAINER_STRENGTH_MODIFIER, 46, ActorDataFormat.INT)
            .insert(ActorDataTypes.BLOCK_TARGET_POS, 47, ActorDataFormat.VECTOR3I)
            .insert(ActorDataTypes.WITHER_INVULNERABLE_TICKS, 48, ActorDataFormat.INT)
            .insert(ActorDataTypes.WITHER_TARGET_A, 49, ActorDataFormat.LONG)
            .insert(ActorDataTypes.WITHER_TARGET_B, 50, ActorDataFormat.LONG)
            .insert(ActorDataTypes.WITHER_TARGET_C, 51, ActorDataFormat.LONG)
            .insert(ActorDataTypes.WITHER_AERIAL_ATTACK, 52, ActorDataFormat.SHORT)
            .insert(ActorDataTypes.WIDTH, 53, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.HEIGHT, 54, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.FUSE_TIME, 55, ActorDataFormat.INT)
            .insert(ActorDataTypes.SEAT_OFFSET, 56, ActorDataFormat.VECTOR3F)
            .insert(ActorDataTypes.SEAT_LOCK_RIDER_ROTATION, 57, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.SEAT_LOCK_RIDER_ROTATION_DEGREES, 58, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.SEAT_HAS_ROTATION, 59, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.AREA_EFFECT_CLOUD_RADIUS, 60, ActorDataFormat.FLOAT)
            .insert(ActorDataTypes.AREA_EFFECT_CLOUD_WAITING, 61, ActorDataFormat.INT)
            .insert(ActorDataTypes.AREA_EFFECT_CLOUD_PARTICLE, 62, ActorDataFormat.INT, new TypeMapTransformer<>(PARTICLE_TYPES))
            .insert(ActorDataTypes.SHULKER_PEEK_AMOUNT, 63, ActorDataFormat.INT)
            .insert(ActorDataTypes.SHULKER_ATTACH_FACE, 64, ActorDataFormat.INT)
            .insert(ActorDataTypes.SHULKER_ATTACHED, 65, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.SHULKER_ATTACH_POS, 66, ActorDataFormat.VECTOR3I)
            .insert(ActorDataTypes.TRADE_TARGET_EID, 67, ActorDataFormat.LONG)
            .insert(ActorDataTypes.CAREER, 68, ActorDataFormat.INT)
            .insert(ActorDataTypes.COMMAND_BLOCK_ENABLED, 69, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.COMMAND_BLOCK_NAME, 70, ActorDataFormat.STRING)
            .insert(ActorDataTypes.COMMAND_BLOCK_LAST_OUTPUT, 71, ActorDataFormat.STRING)
            .insert(ActorDataTypes.COMMAND_BLOCK_TRACK_OUTPUT, 72, ActorDataFormat.BYTE, BooleanTransformer.INSTANCE)
            .insert(ActorDataTypes.CONTROLLING_RIDER_SEAT_INDEX, 73, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.STRENGTH, 74, ActorDataFormat.INT)
            .insert(ActorDataTypes.STRENGTH_MAX, 75, ActorDataFormat.INT)
            .insert(ActorDataTypes.EVOKER_SPELL_CASTING_COLOR, 76, ActorDataFormat.INT)
            .insert(ActorDataTypes.DATA_LIFETIME_TICKS, 77, ActorDataFormat.INT)
            .insert(ActorDataTypes.ARMOR_STAND_POSE_INDEX, 78, ActorDataFormat.INT)
            .insert(ActorDataTypes.END_CRYSTAL_TICK_OFFSET, 79, ActorDataFormat.INT)
            .insert(ActorDataTypes.NAMETAG_ALWAYS_SHOW, 80, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.COLOR_2, 81, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.NAME_AUTHOR, 82, ActorDataFormat.STRING, StringTransformer.INSTANCE)
            .insert(ActorDataTypes.SCORE, 83, ActorDataFormat.STRING, StringTransformer.INSTANCE)
            .insert(ActorDataTypes.BALLOON_ANCHOR_EID, 84, ActorDataFormat.LONG)
            .insert(ActorDataTypes.PUFFED_STATE, 85, ActorDataFormat.BYTE)
            .insert(ActorDataTypes.BOAT_BUBBLE_TIME, 86, ActorDataFormat.INT)
            .insert(ActorDataTypes.AGENT_EID, 87, ActorDataFormat.LONG)
            .build();

    protected static final TypeMap<Class<?>> GAME_RULE_TYPES = TypeMap.<Class<?>>builder("GameRuleType")
            .insert(1, Boolean.class)
            .insert(2, Integer.class)
            .insert(3, Float.class)
            .build();

    protected static final int LEVEL_EVENT_SOUND = 1000;
    protected static final int LEVEL_EVENT_PARTICLE = 2000;
    protected static final int LEVEL_EVENT_WORLD = 3000;
    protected static final int LEVEL_EVENT_BLOCK = 3500;
    protected static final int LEVEL_EVENT_PARTICLE_TYPE = 0x4000;

    @SuppressWarnings("PointlessArithmeticExpression")
    protected static final TypeMap<LevelEventType> LEVEL_EVENTS = TypeMap.builder(LevelEventType.class)
            .insert(0, LevelEvent.UNDEFINED)
            .insert(LEVEL_EVENT_SOUND + 0, LevelEvent.SOUND_CLICK)
            .insert(LEVEL_EVENT_SOUND + 1, LevelEvent.SOUND_CLICK_FAIL)
            .insert(LEVEL_EVENT_SOUND + 2, LevelEvent.SOUND_LAUNCH)
            .insert(LEVEL_EVENT_SOUND + 3, LevelEvent.SOUND_DOOR_OPEN)
            .insert(LEVEL_EVENT_SOUND + 4, LevelEvent.SOUND_FIZZ)
            .insert(LEVEL_EVENT_SOUND + 5, LevelEvent.SOUND_FUSE)
            .insert(LEVEL_EVENT_SOUND + 6, LevelEvent.SOUND_PLAY_RECORDING)
            .insert(LEVEL_EVENT_SOUND + 7, LevelEvent.SOUND_GHAST_WARNING)
            .insert(LEVEL_EVENT_SOUND + 8, LevelEvent.SOUND_GHAST_FIREBALL)
            .insert(LEVEL_EVENT_SOUND + 9, LevelEvent.SOUND_BLAZE_FIREBALL)
            .insert(LEVEL_EVENT_SOUND + 10, LevelEvent.SOUND_ZOMBIE_DOOR_BUMP)
            .insert(LEVEL_EVENT_SOUND + 12, LevelEvent.SOUND_ZOMBIE_DOOR_CRASH)
            .insert(LEVEL_EVENT_SOUND + 16, LevelEvent.SOUND_ZOMBIE_INFECTED)
            .insert(LEVEL_EVENT_SOUND + 17, LevelEvent.SOUND_ZOMBIE_CONVERTED)
            .insert(LEVEL_EVENT_SOUND + 18, LevelEvent.SOUND_ENDERMAN_TELEPORT)
            .insert(LEVEL_EVENT_SOUND + 20, LevelEvent.SOUND_ANVIL_BROKEN)
            .insert(LEVEL_EVENT_SOUND + 21, LevelEvent.SOUND_ANVIL_USED)
            .insert(LEVEL_EVENT_SOUND + 22, LevelEvent.SOUND_ANVIL_LAND)
            .insert(LEVEL_EVENT_SOUND + 30, LevelEvent.SOUND_INFINITY_ARROW_PICKUP)
            .insert(LEVEL_EVENT_SOUND + 32, LevelEvent.SOUND_TELEPORT_ENDERPEARL)
            .insert(LEVEL_EVENT_SOUND + 40, LevelEvent.SOUND_ITEMFRAME_ITEM_ADD)
            .insert(LEVEL_EVENT_SOUND + 41, LevelEvent.SOUND_ITEMFRAME_BREAK)
            .insert(LEVEL_EVENT_SOUND + 42, LevelEvent.SOUND_ITEMFRAME_PLACE)
            .insert(LEVEL_EVENT_SOUND + 43, LevelEvent.SOUND_ITEMFRAME_ITEM_REMOVE)
            .insert(LEVEL_EVENT_SOUND + 44, LevelEvent.SOUND_ITEMFRAME_ITEM_ROTATE)
            .insert(LEVEL_EVENT_SOUND + 51, LevelEvent.SOUND_EXPERIENCE_ORB_PICKUP)
            .insert(LEVEL_EVENT_SOUND + 52, LevelEvent.SOUND_TOTEM_USED)
            .insert(LEVEL_EVENT_SOUND + 60, LevelEvent.SOUND_ARMOR_STAND_BREAK)
            .insert(LEVEL_EVENT_SOUND + 61, LevelEvent.SOUND_ARMOR_STAND_HIT)
            .insert(LEVEL_EVENT_SOUND + 62, LevelEvent.SOUND_ARMOR_STAND_LAND)
            .insert(LEVEL_EVENT_SOUND + 63, LevelEvent.SOUND_ARMOR_STAND_PLACE)
            .insert(LEVEL_EVENT_PARTICLE + 0, LevelEvent.PARTICLE_SHOOT)
            .insert(LEVEL_EVENT_PARTICLE + 1, LevelEvent.PARTICLE_DESTROY_BLOCK)
            .insert(LEVEL_EVENT_PARTICLE + 2, LevelEvent.PARTICLE_POTION_SPLASH)
            .insert(LEVEL_EVENT_PARTICLE + 3, LevelEvent.PARTICLE_EYE_OF_ENDER_DEATH)
            .insert(LEVEL_EVENT_PARTICLE + 4, LevelEvent.PARTICLE_MOB_BLOCK_SPAWN)
            .insert(LEVEL_EVENT_PARTICLE + 5, LevelEvent.PARTICLE_CROP_GROWTH)
            .insert(LEVEL_EVENT_PARTICLE + 6, LevelEvent.PARTICLE_SOUND_GUARDIAN_GHOST)
            .insert(LEVEL_EVENT_PARTICLE + 7, LevelEvent.PARTICLE_DEATH_SMOKE)
            .insert(LEVEL_EVENT_PARTICLE + 8, LevelEvent.PARTICLE_DENY_BLOCK)
            .insert(LEVEL_EVENT_PARTICLE + 9, LevelEvent.PARTICLE_GENERIC_SPAWN)
            .insert(LEVEL_EVENT_PARTICLE + 10, LevelEvent.PARTICLE_DRAGON_EGG)
            .insert(LEVEL_EVENT_PARTICLE + 11, LevelEvent.PARTICLE_CROP_EATEN)
            .insert(LEVEL_EVENT_PARTICLE + 12, LevelEvent.PARTICLE_CRIT)
            .insert(LEVEL_EVENT_PARTICLE + 13, LevelEvent.PARTICLE_TELEPORT)
            .insert(LEVEL_EVENT_PARTICLE + 14, LevelEvent.PARTICLE_CRACK_BLOCK)
            .insert(LEVEL_EVENT_PARTICLE + 15, LevelEvent.PARTICLE_BUBBLES)
            .insert(LEVEL_EVENT_PARTICLE + 16, LevelEvent.PARTICLE_EVAPORATE)
            .insert(LEVEL_EVENT_PARTICLE + 17, LevelEvent.PARTICLE_DESTROY_ARMOR_STAND)
            .insert(LEVEL_EVENT_PARTICLE + 18, LevelEvent.PARTICLE_BREAKING_EGG)
            .insert(LEVEL_EVENT_PARTICLE + 19, LevelEvent.PARTICLE_DESTROY_EGG)
            .insert(LEVEL_EVENT_PARTICLE + 20, LevelEvent.PARTICLE_EVAPORATE_WATER)
            .insert(LEVEL_EVENT_PARTICLE + 21, LevelEvent.PARTICLE_DESTROY_BLOCK_NO_SOUND)
            .insert(LEVEL_EVENT_WORLD + 1, LevelEvent.START_RAINING)
            .insert(LEVEL_EVENT_WORLD + 2, LevelEvent.START_THUNDERSTORM)
            .insert(LEVEL_EVENT_WORLD + 3, LevelEvent.STOP_RAINING)
            .insert(LEVEL_EVENT_WORLD + 4, LevelEvent.STOP_THUNDERSTORM)
            .insert(LEVEL_EVENT_WORLD + 5, LevelEvent.GLOBAL_PAUSE)
            .insert(LEVEL_EVENT_WORLD + 6, LevelEvent.SIM_TIME_STEP)
            .insert(LEVEL_EVENT_WORLD + 7, LevelEvent.SIM_TIME_SCALE)
            .insert(LEVEL_EVENT_BLOCK + 0, LevelEvent.ACTIVATE_BLOCK)
            .insert(LEVEL_EVENT_BLOCK + 1, LevelEvent.CAULDRON_EXPLODE)
            .insert(LEVEL_EVENT_BLOCK + 2, LevelEvent.CAULDRON_DYE_ARMOR)
            .insert(LEVEL_EVENT_BLOCK + 3, LevelEvent.CAULDRON_CLEAN_ARMOR)
            .insert(LEVEL_EVENT_BLOCK + 4, LevelEvent.CAULDRON_FILL_POTION)
            .insert(LEVEL_EVENT_BLOCK + 5, LevelEvent.CAULDRON_TAKE_POTION)
            .insert(LEVEL_EVENT_BLOCK + 6, LevelEvent.CAULDRON_FILL_WATER)
            .insert(LEVEL_EVENT_BLOCK + 7, LevelEvent.CAULDRON_TAKE_WATER)
            .insert(LEVEL_EVENT_BLOCK + 8, LevelEvent.CAULDRON_ADD_DYE)
            .insert(LEVEL_EVENT_BLOCK + 9, LevelEvent.CAULDRON_CLEAN_BANNER)
            .insert(LEVEL_EVENT_BLOCK + 10, LevelEvent.CAULDRON_FLUSH)
            .insert(LEVEL_EVENT_PARTICLE_TYPE, PARTICLE_TYPES)
            .build();

    protected static final TypeMap<LevelSoundEvent> SOUND_EVENTS = TypeMap.builder(LevelSoundEvent.class)
            .insert(0, LevelSoundEvent.ITEM_USE_ON)
            .insert(1, LevelSoundEvent.HIT)
            .insert(2, LevelSoundEvent.STEP)
            .insert(3, LevelSoundEvent.FLY)
            .insert(4, LevelSoundEvent.JUMP)
            .insert(5, LevelSoundEvent.BREAK)
            .insert(6, LevelSoundEvent.PLACE)
            .insert(7, LevelSoundEvent.HEAVY_STEP)
            .insert(8, LevelSoundEvent.GALLOP)
            .insert(9, LevelSoundEvent.FALL)
            .insert(10, LevelSoundEvent.AMBIENT)
            .insert(11, LevelSoundEvent.AMBIENT_BABY)
            .insert(12, LevelSoundEvent.AMBIENT_IN_WATER)
            .insert(13, LevelSoundEvent.BREATHE)
            .insert(14, LevelSoundEvent.DEATH)
            .insert(15, LevelSoundEvent.DEATH_IN_WATER)
            .insert(16, LevelSoundEvent.DEATH_TO_ZOMBIE)
            .insert(17, LevelSoundEvent.HURT)
            .insert(18, LevelSoundEvent.HURT_IN_WATER)
            .insert(19, LevelSoundEvent.MAD)
            .insert(20, LevelSoundEvent.BOOST)
            .insert(21, LevelSoundEvent.BOW)
            .insert(22, LevelSoundEvent.SQUISH_BIG)
            .insert(23, LevelSoundEvent.SQUISH_SMALL)
            .insert(24, LevelSoundEvent.FALL_BIG)
            .insert(25, LevelSoundEvent.FALL_SMALL)
            .insert(26, LevelSoundEvent.SPLASH)
            .insert(27, LevelSoundEvent.FIZZ)
            .insert(28, LevelSoundEvent.FLAP)
            .insert(29, LevelSoundEvent.SWIM)
            .insert(30, LevelSoundEvent.DRINK)
            .insert(31, LevelSoundEvent.EAT)
            .insert(32, LevelSoundEvent.TAKEOFF)
            .insert(33, LevelSoundEvent.SHAKE)
            .insert(34, LevelSoundEvent.PLOP)
            .insert(35, LevelSoundEvent.LAND)
            .insert(36, LevelSoundEvent.SADDLE)
            .insert(37, LevelSoundEvent.ARMOR)
            .insert(38, LevelSoundEvent.MOB_ARMOR_STAND_PLACE)
            .insert(39, LevelSoundEvent.ADD_CHEST)
            .insert(40, LevelSoundEvent.THROW)
            .insert(41, LevelSoundEvent.ATTACK)
            .insert(42, LevelSoundEvent.ATTACK_NODAMAGE)
            .insert(43, LevelSoundEvent.ATTACK_STRONG)
            .insert(44, LevelSoundEvent.WARN)
            .insert(45, LevelSoundEvent.SHEAR)
            .insert(46, LevelSoundEvent.MILK)
            .insert(47, LevelSoundEvent.THUNDER)
            .insert(48, LevelSoundEvent.EXPLODE)
            .insert(49, LevelSoundEvent.FIRE)
            .insert(50, LevelSoundEvent.IGNITE)
            .insert(51, LevelSoundEvent.FUSE)
            .insert(52, LevelSoundEvent.STARE)
            .insert(53, LevelSoundEvent.SPAWN)
            .insert(54, LevelSoundEvent.SHOOT)
            .insert(55, LevelSoundEvent.BREAK_BLOCK)
            .insert(56, LevelSoundEvent.LAUNCH)
            .insert(57, LevelSoundEvent.BLAST)
            .insert(58, LevelSoundEvent.LARGE_BLAST)
            .insert(59, LevelSoundEvent.TWINKLE)
            .insert(60, LevelSoundEvent.REMEDY)
            .insert(61, LevelSoundEvent.UNFECT)
            .insert(62, LevelSoundEvent.LEVELUP)
            .insert(63, LevelSoundEvent.BOW_HIT)
            .insert(64, LevelSoundEvent.BULLET_HIT)
            .insert(65, LevelSoundEvent.EXTINGUISH_FIRE)
            .insert(66, LevelSoundEvent.ITEM_FIZZ)
            .insert(67, LevelSoundEvent.CHEST_OPEN)
            .insert(68, LevelSoundEvent.CHEST_CLOSED)
            .insert(69, LevelSoundEvent.SHULKERBOX_OPEN)
            .insert(70, LevelSoundEvent.SHULKERBOX_CLOSED)
            .insert(71, LevelSoundEvent.ENDERCHEST_OPEN)
            .insert(72, LevelSoundEvent.ENDERCHEST_CLOSED)
            .insert(73, LevelSoundEvent.POWER_ON)
            .insert(74, LevelSoundEvent.POWER_OFF)
            .insert(75, LevelSoundEvent.ATTACH)
            .insert(76, LevelSoundEvent.DETACH)
            .insert(77, LevelSoundEvent.DENY)
            .insert(78, LevelSoundEvent.TRIPOD)
            .insert(79, LevelSoundEvent.POP)
            .insert(80, LevelSoundEvent.DROP_SLOT)
            .insert(81, LevelSoundEvent.NOTE)
            .insert(82, LevelSoundEvent.THORNS)
            .insert(83, LevelSoundEvent.PISTON_IN)
            .insert(84, LevelSoundEvent.PISTON_OUT)
            .insert(85, LevelSoundEvent.PORTAL)
            .insert(86, LevelSoundEvent.WATER)
            .insert(87, LevelSoundEvent.LAVA_POP)
            .insert(88, LevelSoundEvent.LAVA)
            .insert(89, LevelSoundEvent.BURP)
            .insert(90, LevelSoundEvent.BUCKET_FILL_WATER)
            .insert(91, LevelSoundEvent.BUCKET_FILL_LAVA)
            .insert(92, LevelSoundEvent.BUCKET_EMPTY_WATER)
            .insert(93, LevelSoundEvent.BUCKET_EMPTY_LAVA)
            .insert(94, LevelSoundEvent.ARMOR_EQUIP_CHAIN)
            .insert(95, LevelSoundEvent.ARMOR_EQUIP_DIAMOND)
            .insert(96, LevelSoundEvent.ARMOR_EQUIP_GENERIC)
            .insert(97, LevelSoundEvent.ARMOR_EQUIP_GOLD)
            .insert(98, LevelSoundEvent.ARMOR_EQUIP_IRON)
            .insert(99, LevelSoundEvent.ARMOR_EQUIP_LEATHER)
            .insert(100, LevelSoundEvent.ARMOR_EQUIP_ELYTRA)
            .insert(101, LevelSoundEvent.RECORD_13)
            .insert(102, LevelSoundEvent.RECORD_CAT)
            .insert(103, LevelSoundEvent.RECORD_BLOCKS)
            .insert(104, LevelSoundEvent.RECORD_CHIRP)
            .insert(105, LevelSoundEvent.RECORD_FAR)
            .insert(106, LevelSoundEvent.RECORD_MALL)
            .insert(107, LevelSoundEvent.RECORD_MELLOHI)
            .insert(108, LevelSoundEvent.RECORD_STAL)
            .insert(109, LevelSoundEvent.RECORD_STRAD)
            .insert(110, LevelSoundEvent.RECORD_WARD)
            .insert(111, LevelSoundEvent.RECORD_11)
            .insert(112, LevelSoundEvent.RECORD_WAIT)
            .insert(113, LevelSoundEvent.STOP_RECORD)
            .insert(114, LevelSoundEvent.FLOP)
            .insert(115, LevelSoundEvent.ELDERGUARDIAN_CURSE)
            .insert(116, LevelSoundEvent.MOB_WARNING)
            .insert(117, LevelSoundEvent.MOB_WARNING_BABY)
            .insert(118, LevelSoundEvent.TELEPORT)
            .insert(119, LevelSoundEvent.SHULKER_OPEN)
            .insert(120, LevelSoundEvent.SHULKER_CLOSE)
            .insert(121, LevelSoundEvent.HAGGLE)
            .insert(122, LevelSoundEvent.HAGGLE_YES)
            .insert(123, LevelSoundEvent.HAGGLE_NO)
            .insert(124, LevelSoundEvent.HAGGLE_IDLE)
            .insert(125, LevelSoundEvent.CHORUS_GROW)
            .insert(126, LevelSoundEvent.CHORUS_DEATH)
            .insert(127, LevelSoundEvent.GLASS)
            .insert(128, LevelSoundEvent.POTION_BREWED)
            .insert(129, LevelSoundEvent.CAST_SPELL)
            .insert(130, LevelSoundEvent.PREPARE_ATTACK)
            .insert(131, LevelSoundEvent.PREPARE_SUMMON)
            .insert(132, LevelSoundEvent.PREPARE_WOLOLO)
            .insert(133, LevelSoundEvent.FANG)
            .insert(134, LevelSoundEvent.CHARGE)
            .insert(135, LevelSoundEvent.CAMERA_TAKE_PICTURE)
            .insert(136, LevelSoundEvent.LEASHKNOT_PLACE)
            .insert(137, LevelSoundEvent.LEASHKNOT_BREAK)
            .insert(138, LevelSoundEvent.GROWL)
            .insert(139, LevelSoundEvent.WHINE)
            .insert(140, LevelSoundEvent.PANT)
            .insert(141, LevelSoundEvent.PURR)
            .insert(142, LevelSoundEvent.PURREOW)
            .insert(143, LevelSoundEvent.DEATH_MIN_VOLUME)
            .insert(144, LevelSoundEvent.DEATH_MID_VOLUME)
            .insert(145, LevelSoundEvent.IMITATE_BLAZE)
            .insert(146, LevelSoundEvent.IMITATE_CAVE_SPIDER)
            .insert(147, LevelSoundEvent.IMITATE_CREEPER)
            .insert(148, LevelSoundEvent.IMITATE_ELDER_GUARDIAN)
            .insert(149, LevelSoundEvent.IMITATE_ENDER_DRAGON)
            .insert(150, LevelSoundEvent.IMITATE_ENDERMAN)
            .insert(151, LevelSoundEvent.IMITATE_ENDERMITE)
            .insert(152, LevelSoundEvent.IMITATE_EVOCATION_ILLAGER)
            .insert(153, LevelSoundEvent.IMITATE_GHAST)
            .insert(154, LevelSoundEvent.IMITATE_HUSK)
            .insert(155, LevelSoundEvent.IMITATE_ILLUSION_ILLAGER)
            .insert(156, LevelSoundEvent.IMITATE_MAGMA_CUBE)
            .insert(157, LevelSoundEvent.IMITATE_POLAR_BEAR)
            .insert(158, LevelSoundEvent.IMITATE_SHULKER)
            .insert(159, LevelSoundEvent.IMITATE_SILVERFISH)
            .insert(160, LevelSoundEvent.IMITATE_SKELETON)
            .insert(161, LevelSoundEvent.IMITATE_SLIME)
            .insert(162, LevelSoundEvent.IMITATE_SPIDER)
            .insert(163, LevelSoundEvent.IMITATE_STRAY)
            .insert(164, LevelSoundEvent.IMITATE_VEX)
            .insert(165, LevelSoundEvent.IMITATE_VINDICATION_ILLAGER)
            .insert(166, LevelSoundEvent.IMITATE_WITCH)
            .insert(167, LevelSoundEvent.IMITATE_WITHER)
            .insert(168, LevelSoundEvent.IMITATE_WITHER_SKELETON)
            .insert(169, LevelSoundEvent.IMITATE_WOLF)
            .insert(170, LevelSoundEvent.IMITATE_ZOMBIE)
            .insert(171, LevelSoundEvent.IMITATE_ZOMBIE_PIGMAN)
            .insert(172, LevelSoundEvent.IMITATE_ZOMBIE_VILLAGER)
            .insert(173, LevelSoundEvent.BLOCK_END_PORTAL_FRAME_FILL)
            .insert(174, LevelSoundEvent.BLOCK_END_PORTAL_SPAWN)
            .insert(175, LevelSoundEvent.RANDOM_ANVIL_USE)
            .insert(176, LevelSoundEvent.BOTTLE_DRAGONBREATH)
            .insert(177, LevelSoundEvent.PORTAL_TRAVEL)
            .insert(178, LevelSoundEvent.ITEM_TRIDENT_HIT)
            .insert(179, LevelSoundEvent.ITEM_TRIDENT_RETURN)
            .insert(180, LevelSoundEvent.ITEM_TRIDENT_RIPTIDE_1)
            .insert(181, LevelSoundEvent.ITEM_TRIDENT_RIPTIDE_2)
            .insert(182, LevelSoundEvent.ITEM_TRIDENT_RIPTIDE_3)
            .insert(183, LevelSoundEvent.ITEM_TRIDENT_THROW)
            .insert(184, LevelSoundEvent.ITEM_TRIDENT_THUNDER)
            .insert(185, LevelSoundEvent.ITEM_TRIDENT_HIT_GROUND)
            .insert(186, LevelSoundEvent.DEFAULT)
            .insert(188, LevelSoundEvent.ELEMENT_CONSTRUCTOR_OPEN)
            .insert(189, LevelSoundEvent.ICE_BOMB_HIT)
            .insert(190, LevelSoundEvent.BALLOON_POP)
            .insert(191, LevelSoundEvent.LT_REACTION_ICE_BOMB)
            .insert(192, LevelSoundEvent.LT_REACTION_BLEACH)
            .insert(193, LevelSoundEvent.LT_REACTION_E_PASTE)
            .insert(194, LevelSoundEvent.LT_REACTION_E_PASTE2)
            .insert(199, LevelSoundEvent.LT_REACTION_FERTILIZER)
            .insert(200, LevelSoundEvent.LT_REACTION_FIREBALL)
            .insert(201, LevelSoundEvent.LT_REACTION_MG_SALT)
            .insert(202, LevelSoundEvent.LT_REACTION_MISC_FIRE)
            .insert(203, LevelSoundEvent.LT_REACTION_FIRE)
            .insert(204, LevelSoundEvent.LT_REACTION_MISC_EXPLOSION)
            .insert(205, LevelSoundEvent.LT_REACTION_MISC_MYSTICAL)
            .insert(206, LevelSoundEvent.LT_REACTION_MISC_MYSTICAL2)
            .insert(207, LevelSoundEvent.LT_REACTION_PRODUCT)
            .insert(208, LevelSoundEvent.SPARKLER_USE)
            .insert(209, LevelSoundEvent.GLOWSTICK_USE)
            .insert(210, LevelSoundEvent.SPARKLER_ACTIVE)
            .insert(211, LevelSoundEvent.CONVERT_TO_DROWNED)
            .insert(212, LevelSoundEvent.BUCKET_FILL_FISH)
            .insert(213, LevelSoundEvent.BUCKET_EMPTY_FISH)
            .insert(214, LevelSoundEvent.BUBBLE_UP)
            .insert(215, LevelSoundEvent.BUBBLE_DOWN)
            .insert(216, LevelSoundEvent.BUBBLE_POP)
            .insert(217, LevelSoundEvent.BUBBLE_UP_INSIDE)
            .insert(218, LevelSoundEvent.BUBBLE_DOWN_INSIDE)
            .insert(219, LevelSoundEvent.BABY_HURT)
            .insert(220, LevelSoundEvent.BABY_DEATH)
            .insert(221, LevelSoundEvent.BABY_STEP)
            .insert(222, LevelSoundEvent.BABY_SPAWN)
            .insert(223, LevelSoundEvent.BORN)
            .insert(224, LevelSoundEvent.BLOCK_TURTLE_EGG_BREAK)
            .insert(225, LevelSoundEvent.BLOCK_TURTLE_EGG_CRACK)
            .insert(226, LevelSoundEvent.BLOCK_TURTLE_EGG_HATCH)
            .insert(227, LevelSoundEvent.TURTLE_LAY_EGG)
            .insert(228, LevelSoundEvent.BLOCK_TURTLE_EGG_ATTACK)
            .insert(229, LevelSoundEvent.BEACON_ACTIVATE)
            .insert(230, LevelSoundEvent.BEACON_AMBIENT)
            .insert(231, LevelSoundEvent.BEACON_DEACTIVATE)
            .insert(232, LevelSoundEvent.BEACON_POWER)
            .insert(233, LevelSoundEvent.CONDUIT_ACTIVATE)
            .insert(234, LevelSoundEvent.CONDUIT_AMBIENT)
            .insert(235, LevelSoundEvent.CONDUIT_ATTACK)
            .insert(236, LevelSoundEvent.CONDUIT_DEACTIVATE)
            .insert(237, LevelSoundEvent.CONDUIT_SHORT)
            .insert(238, LevelSoundEvent.SWOOP)
            .insert(239, LevelSoundEvent.UNDEFINED)
            .build();

    protected static final TypeMap<ActorEvent> ACTOR_EVENTS = TypeMap.builder(ActorEvent.class)
            .insert(0, ActorEvent.NONE)
            .insert(1, ActorEvent.JUMP)
            .insert(2, ActorEvent.HURT)
            .insert(3, ActorEvent.DEATH)
            .insert(4, ActorEvent.START_ATTACKING)
            .insert(5, ActorEvent.STOP_ATTACKING)
            .insert(6, ActorEvent.TAMING_FAILED)
            .insert(7, ActorEvent.TAMING_SUCCEEDED)
            .insert(8, ActorEvent.SHAKE_WETNESS)
            .insert(9, ActorEvent.USE_ITEM)
            .insert(10, ActorEvent.EAT_GRASS)
            .insert(11, ActorEvent.FISHHOOK_BUBBLE)
            .insert(12, ActorEvent.FISHHOOK_FISHPOS)
            .insert(13, ActorEvent.FISHHOOK_HOOKTIME)
            .insert(14, ActorEvent.FISHHOOK_TEASE)
            .insert(15, ActorEvent.SQUID_FLEEING)
            .insert(16, ActorEvent.ZOMBIE_CONVERTING)
            .insert(17, ActorEvent.PLAY_AMBIENT)
            .insert(18, ActorEvent.SPAWN_ALIVE)
            .insert(19, ActorEvent.START_OFFER_FLOWER)
            .insert(20, ActorEvent.STOP_OFFER_FLOWER)
            .insert(21, ActorEvent.LOVE_HEARTS)
            .insert(22, ActorEvent.VILLAGER_ANGRY)
            .insert(23, ActorEvent.VILLAGER_HAPPY)
            .insert(24, ActorEvent.WITCH_HAT_MAGIC)
            .insert(25, ActorEvent.FIREWORKS_EXPLODE)
            .insert(26, ActorEvent.IN_LOVE_HEARTS)
            .insert(27, ActorEvent.SILVERFISH_MERGE_ANIM)
            .insert(28, ActorEvent.GUARDIAN_ATTACK_SOUND)
            .insert(29, ActorEvent.DRINK_POTION)
            .insert(30, ActorEvent.THROW_POTION)
            .insert(31, ActorEvent.PRIME_TNTCART)
            .insert(32, ActorEvent.PRIME_CREEPER)
            .insert(33, ActorEvent.AIR_SUPPLY)
            .insert(34, ActorEvent.DEPRECATED_ADD_PLAYER_LEVELS)
            .insert(35, ActorEvent.GUARDIAN_MINING_FATIGUE)
            .insert(36, ActorEvent.AGENT_SWING_ARM)
            .insert(37, ActorEvent.DRAGON_START_DEATH_ANIM)
            .insert(38, ActorEvent.GROUND_DUST)
            .insert(39, ActorEvent.SHAKE)
            // gap
            .insert(57, ActorEvent.FEED)
            .insert(60, ActorEvent.BABY_AGE)
            .insert(61, ActorEvent.INSTANT_DEATH)
            .insert(62, ActorEvent.NOTIFY_TRADE)
            .insert(63, ActorEvent.LEASH_DESTROYED)
            .insert(64, ActorEvent.CARAVAN_UPDATED)
            .insert(65, ActorEvent.TALISMAN_ACTIVATE)
            .insert(66, ActorEvent.DEPRECATED_UPDATE_STRUCTURE_FEATURE)
            .insert(67, ActorEvent.PLAYER_SPAWNED_MOB)
            .insert(68, ActorEvent.PUKE)
            .insert(69, ActorEvent.UPDATE_STACK_SIZE)
            .insert(70, ActorEvent.START_SWIMMING)
            .insert(71, ActorEvent.BALLOON_POP)
            .insert(72, ActorEvent.TREASURE_HUNT)
            .build();

    public static TypeMap<CommandParam> COMMAND_PARAMS = TypeMap.builder(CommandParam.class)
            .insert(1, CommandParam.INT)
            .insert(2, CommandParam.FLOAT)
            .insert(3, CommandParam.VAL)
            .insert(4, CommandParam.WILDCARD_INT)
            .insert(5, CommandParam.OPERATOR)
            .insert(6, CommandParam.SELECTION)
            .insert(7, CommandParam.WILDCARD_SELECTION)
            .insert(24, CommandParam.ID)
            .insert(26, CommandParam.POSITION_FLOAT)
            .insert(29, CommandParam.MESSAGE)
            .insert(31, CommandParam.RAW_TEXT)
            .insert(34, CommandParam.JSON_OBJECT)
            .insert(41, CommandParam.COMMAND)
            .build();

    public static final BedrockCodec CODEC = BedrockCodec.builder()
            .protocolVersion(291)
            .minecraftVersion("1.7.0")
            .helper(() -> new BedrockCodecHelper_v291(ENTITY_DATA, GAME_RULE_TYPES))
            .registerPacket(LoginPacket::new, LoginSerializer_v291.INSTANCE, 1, PacketRecipient.SERVER)
            .registerPacket(PlayStatusPacket::new, PlayStatusSerializer_v291.INSTANCE, 2, PacketRecipient.CLIENT)
            .registerPacket(ServerToClientHandshakePacket::new, ServerToClientHandshakeSerializer_v291.INSTANCE, 3, PacketRecipient.CLIENT)
            .registerPacket(ClientToServerHandshakePacket::new, ClientToServerHandshakeSerializer_v291.INSTANCE, 4, PacketRecipient.SERVER)
            .registerPacket(DisconnectPacket::new, DisconnectSerializer_v291.INSTANCE, 5, PacketRecipient.BOTH)
            .registerPacket(ResourcePacksInfoPacket::new, ResourcePacksInfoSerializer_v291.INSTANCE, 6, PacketRecipient.CLIENT)
            .registerPacket(ResourcePackStackPacket::new, ResourcePackStackSerializer_v291.INSTANCE, 7, PacketRecipient.CLIENT)
            .registerPacket(ResourcePackClientResponsePacket::new, ResourcePackClientResponseSerializer_v291.INSTANCE, 8, PacketRecipient.SERVER)
            .registerPacket(TextPacket::new, TextSerializer_v291.INSTANCE, 9, PacketRecipient.BOTH)
            .registerPacket(SetTimePacket::new, SetTimeSerializer_v291.INSTANCE, 10, PacketRecipient.CLIENT)
            .registerPacket(StartGamePacket::new, StartGameSerializer_v291.INSTANCE, 11, PacketRecipient.CLIENT)
            .registerPacket(AddPlayerPacket::new, AddPlayerSerializer_v291.INSTANCE, 12, PacketRecipient.CLIENT)
            .registerPacket(AddActorPacket::new, AddActorSerializer_v291.INSTANCE, 13, PacketRecipient.CLIENT)
            .registerPacket(RemoveActorPacket::new, RemoveEntitySerializer_v291.INSTANCE, 14, PacketRecipient.CLIENT)
            .registerPacket(AddItemActorPacket::new, AddItemActorSerializer_v291.INSTANCE, 15, PacketRecipient.CLIENT)
            .registerPacket(AddHangingEntityPacket::new, AddHangingEntitySerializer_v291.INSTANCE, 16, PacketRecipient.CLIENT)
            .registerPacket(TakeItemActorPacket::new, TakeItemEntitySerializer_v291.INSTANCE, 17, PacketRecipient.CLIENT)
            .registerPacket(MoveActorAbsolutePacket::new, MoveEntityAbsoluteSerializer_v291.INSTANCE, 18, PacketRecipient.BOTH)
            .registerPacket(MovePlayerPacket::new, MovePlayerSerializer_v291.INSTANCE, 19, PacketRecipient.BOTH)
            .registerPacket(RiderJumpPacket::new, RiderJumpSerializer_v291.INSTANCE, 20, PacketRecipient.SERVER)
            .registerPacket(UpdateBlockPacket::new, UpdateBlockSerializer_v291.INSTANCE, 21, PacketRecipient.CLIENT)
            .registerPacket(AddPaintingPacket::new, AddPaintingSerializer_v291.INSTANCE, 22, PacketRecipient.CLIENT)
            .registerPacket(ExplodePacket::new, ExplodeSerializer_v291.INSTANCE, 23, PacketRecipient.CLIENT)
            .registerPacket(LevelSoundEvent1Packet::new, new LevelSoundEvent1Serializer_v291(SOUND_EVENTS), 24, PacketRecipient.BOTH)
            .registerPacket(LevelEventPacket::new, new LevelEventSerializer_v291(LEVEL_EVENTS), 25, PacketRecipient.CLIENT)
            .registerPacket(BlockEventPacket::new, BlockEventSerializer_v291.INSTANCE, 26, PacketRecipient.CLIENT)
            .registerPacket(ActorEventPacket::new, new ActorEventSerializer_v291(ACTOR_EVENTS), 27, PacketRecipient.BOTH)
            .registerPacket(MobEffectPacket::new, MobEffectSerializer_v291.INSTANCE, 28, PacketRecipient.CLIENT)
            .registerPacket(UpdateAttributesPacket::new, UpdateAttributesSerializer_v291.INSTANCE, 29, PacketRecipient.CLIENT)
            .registerPacket(InventoryTransactionPacket::new, InventoryTransactionSerializer_v291.INSTANCE, 30, PacketRecipient.BOTH)
            .registerPacket(MobEquipmentPacket::new, MobEquipmentSerializer_v291.INSTANCE, 31, PacketRecipient.BOTH)
            .registerPacket(MobArmorEquipmentPacket::new, MobArmorEquipmentSerializer_v291.INSTANCE, 32, PacketRecipient.BOTH)
            .registerPacket(InteractPacket::new, InteractSerializer_v291.INSTANCE, 33, PacketRecipient.SERVER)
            .registerPacket(BlockPickRequestPacket::new, BlockPickRequestSerializer_v291.INSTANCE, 34, PacketRecipient.SERVER)
            .registerPacket(ActorPickRequestPacket::new, ActorPickRequestSerializer_v291.INSTANCE, 35, PacketRecipient.SERVER)
            .registerPacket(PlayerActionPacket::new, PlayerActionSerializer_v291.INSTANCE, 36, PacketRecipient.BOTH)
            .registerPacket(EntityFallPacket::new, EntityFallSerializer_v291.INSTANCE, 37, PacketRecipient.SERVER)
            .registerPacket(HurtArmorPacket::new, HurtArmorSerializer_v291.INSTANCE, 38, PacketRecipient.CLIENT)
            .registerPacket(SetActorDataPacket::new, SetEntityDataSerializer_v291.INSTANCE, 39, PacketRecipient.BOTH)
            .registerPacket(SetActorMotionPacket::new, SetEntityMotionSerializer_v291.INSTANCE, 40, PacketRecipient.BOTH)
            .registerPacket(SetActorLinkPacket::new, SetActorLinkSerializer_v291.INSTANCE, 41, PacketRecipient.BOTH)
            .registerPacket(SetHealthPacket::new, SetHealthSerializer_v291.INSTANCE, 42, PacketRecipient.CLIENT)
            .registerPacket(SetSpawnPositionPacket::new, SetSpawnPositionSerializer_v291.INSTANCE, 43, PacketRecipient.CLIENT)
            .registerPacket(AnimatePacket::new, AnimateSerializer_v291.INSTANCE, 44, PacketRecipient.BOTH)
            .registerPacket(RespawnPacket::new, RespawnSerializer_v291.INSTANCE, 45, PacketRecipient.BOTH)
            .registerPacket(ContainerOpenPacket::new, ContainerOpenSerializer_v291.INSTANCE, 46, PacketRecipient.CLIENT)
            .registerPacket(ContainerClosePacket::new, ContainerCloseSerializer_v291.INSTANCE, 47, PacketRecipient.BOTH)
            .registerPacket(PlayerHotbarPacket::new, PlayerHotbarSerializer_v291.INSTANCE, 48, PacketRecipient.BOTH)
            .registerPacket(InventoryContentPacket::new, InventoryContentSerializer_v291.INSTANCE, 49, PacketRecipient.CLIENT)
            .registerPacket(InventorySlotPacket::new, InventorySlotSerializer_v291.INSTANCE, 50, PacketRecipient.CLIENT)
            .registerPacket(ContainerSetDataPacket::new, ContainerSetDataSerializer_v291.INSTANCE, 51, PacketRecipient.CLIENT)
            .registerPacket(CraftingDataPacket::new, CraftingDataSerializer_v291.INSTANCE, 52, PacketRecipient.CLIENT)
            .registerPacket(CraftingEventPacket::new, CraftingEventSerializer_v291.INSTANCE, 53, PacketRecipient.BOTH)
            .registerPacket(GuiDataPickItemPacket::new, GuiDataPickItemSerializer_v291.INSTANCE, 54, PacketRecipient.CLIENT)
            .registerPacket(AdventureSettingsPacket::new, AdventureSettingsSerializer_v291.INSTANCE, 55, PacketRecipient.BOTH)
            .registerPacket(BlockActorDataPacket::new, BlockEntityDataSerializer_v291.INSTANCE, 56, PacketRecipient.BOTH)
            .registerPacket(PlayerInputPacket::new, PlayerInputSerializer_v291.INSTANCE, 57, PacketRecipient.SERVER)
            .registerPacket(LevelChunkPacket::new, FullChunkDataSerializer_v291.INSTANCE, 58, PacketRecipient.CLIENT)
            .registerPacket(SetCommandsEnabledPacket::new, SetCommandsEnabledSerializer_v291.INSTANCE, 59, PacketRecipient.CLIENT)
            .registerPacket(SetDifficultyPacket::new, SetDifficultySerializer_v291.INSTANCE, 60, PacketRecipient.BOTH)
            .registerPacket(ChangeDimensionPacket::new, ChangeDimensionSerializer_v291.INSTANCE, 61, PacketRecipient.CLIENT)
            .registerPacket(SetPlayerGameTypePacket::new, SetPlayerGameTypeSerializer_v291.INSTANCE, 62, PacketRecipient.BOTH)
            .registerPacket(PlayerListPacket::new, PlayerListSerializer_v291.INSTANCE, 63, PacketRecipient.CLIENT)
            .registerPacket(SimpleEventPacket::new, SimpleEventSerializer_v291.INSTANCE, 64, PacketRecipient.BOTH)
            .registerPacket(LegacyTelemetryEventPacket::new, LegacyTelemetryEventSerializer_v291.INSTANCE, 65, PacketRecipient.CLIENT)
            .registerPacket(SpawnExperienceOrbPacket::new, SpawnExperienceOrbSerializer_v291.INSTANCE, 66, PacketRecipient.CLIENT)
            .registerPacket(ClientboundMapItemDataPacket::new, ClientboundMapItemDataSerializer_v291.INSTANCE, 67, PacketRecipient.CLIENT)
            .registerPacket(MapInfoRequestPacket::new, MapInfoRequestSerializer_v291.INSTANCE, 68, PacketRecipient.SERVER)
            .registerPacket(RequestChunkRadiusPacket::new, RequestChunkRadiusSerializer_v291.INSTANCE, 69, PacketRecipient.SERVER)
            .registerPacket(ChunkRadiusUpdatedPacket::new, ChunkRadiusUpdatedSerializer_v291.INSTANCE, 70, PacketRecipient.CLIENT)
            .registerPacket(ItemFrameDropItemPacket::new, ItemFrameDropItemSerializer_v291.INSTANCE, 71, PacketRecipient.SERVER)
            .registerPacket(GameRulesChangedPacket::new, GameRulesChangedSerializer_v291.INSTANCE, 72, PacketRecipient.CLIENT)
            .registerPacket(CameraPacket::new, CameraSerializer_v291.INSTANCE, 73, PacketRecipient.CLIENT)
            .registerPacket(BossEventPacket::new, BossEventSerializer_v291.INSTANCE, 74, PacketRecipient.BOTH)
            .registerPacket(ShowCreditsPacket::new, ShowCreditsSerializer_v291.INSTANCE, 75, PacketRecipient.BOTH)
            .registerPacket(AvailableCommandsPacket::new, new AvailableCommandsSerializer_v291(COMMAND_PARAMS), 76, PacketRecipient.CLIENT)
            .registerPacket(CommandRequestPacket::new, CommandRequestSerializer_v291.INSTANCE, 77, PacketRecipient.SERVER)
            .registerPacket(CommandBlockUpdatePacket::new, CommandBlockUpdateSerializer_v291.INSTANCE, 78, PacketRecipient.SERVER)
            .registerPacket(CommandOutputPacket::new, CommandOutputSerializer_v291.INSTANCE, 79, PacketRecipient.CLIENT)
            .registerPacket(UpdateTradePacket::new, UpdateTradeSerializer_v291.INSTANCE, 80, PacketRecipient.CLIENT)
            .registerPacket(UpdateEquipPacket::new, UpdateEquipSerializer_v291.INSTANCE, 81, PacketRecipient.CLIENT)
            .registerPacket(ResourcePackDataInfoPacket::new, ResourcePackDataInfoSerializer_v291.INSTANCE, 82, PacketRecipient.CLIENT)
            .registerPacket(ResourcePackChunkDataPacket::new, ResourcePackChunkDataSerializer_v291.INSTANCE, 83, PacketRecipient.CLIENT)
            .registerPacket(ResourcePackChunkRequestPacket::new, ResourcePackChunkRequestSerializer_v291.INSTANCE, 84, PacketRecipient.SERVER)
            .registerPacket(TransferPacket::new, TransferSerializer_v291.INSTANCE, 85, PacketRecipient.CLIENT)
            .registerPacket(PlaySoundPacket::new, PlaySoundSerializer_v291.INSTANCE, 86, PacketRecipient.CLIENT)
            .registerPacket(StopSoundPacket::new, StopSoundSerializer_v291.INSTANCE, 87, PacketRecipient.CLIENT)
            .registerPacket(SetTitlePacket::new, SetTitleSerializer_v291.INSTANCE, 88, PacketRecipient.CLIENT)
            .registerPacket(AddBehaviorTreePacket::new, AddBehaviorTreeSerializer_v291.INSTANCE, 89, PacketRecipient.CLIENT)
            .registerPacket(StructureBlockUpdatePacket::new, StructureBlockUpdateSerializer_v291.INSTANCE, 90, PacketRecipient.SERVER)
            .registerPacket(ShowStoreOfferPacket::new, ShowStoreOfferSerializer_v291.INSTANCE, 91, PacketRecipient.CLIENT)
            .registerPacket(PurchaseReceiptPacket::new, PurchaseReceiptSerializer_v291.INSTANCE, 92, PacketRecipient.SERVER)
            .registerPacket(PlayerSkinPacket::new, PlayerSkinSerializer_v291.INSTANCE, 93, PacketRecipient.BOTH)
            .registerPacket(SubClientLoginPacket::new, SubClientLoginSerializer_v291.INSTANCE, 94, PacketRecipient.SERVER)
            .registerPacket(AutomationClientConnectPacket::new, AutomationClientConnectSerializer_v291.INSTANCE, 95, PacketRecipient.CLIENT)
            .registerPacket(SetLastHurtByPacket::new, SetLastHurtBySerializer_v291.INSTANCE, 96, PacketRecipient.CLIENT)
            .registerPacket(BookEditPacket::new, BookEditSerializer_v291.INSTANCE, 97, PacketRecipient.SERVER)
            .registerPacket(NpcRequestPacket::new, NpcRequestSerializer_v291.INSTANCE, 98, PacketRecipient.SERVER)
            .registerPacket(PhotoTransferPacket::new, PhotoTransferSerializer_v291.INSTANCE, 99, PacketRecipient.CLIENT)
            .registerPacket(ModalFormRequestPacket::new, ModalFormRequestSerializer_v291.INSTANCE, 100, PacketRecipient.CLIENT)
            .registerPacket(ModalFormResponsePacket::new, ModalFormResponseSerializer_v291.INSTANCE, 101, PacketRecipient.SERVER)
            .registerPacket(ServerSettingsRequestPacket::new, ServerSettingsRequestSerializer_v291.INSTANCE, 102, PacketRecipient.SERVER)
            .registerPacket(ServerSettingsResponsePacket::new, ServerSettingsResponseSerializer_v291.INSTANCE, 103, PacketRecipient.CLIENT)
            .registerPacket(ShowProfilePacket::new, ShowProfileSerializer_v291.INSTANCE, 104, PacketRecipient.CLIENT)
            .registerPacket(SetDefaultGameTypePacket::new, SetDefaultGameTypeSerializer_v291.INSTANCE, 105, PacketRecipient.BOTH)
            .registerPacket(RemoveObjectivePacket::new, RemoveObjectiveSerializer_v291.INSTANCE, 106, PacketRecipient.CLIENT)
            .registerPacket(SetDisplayObjectivePacket::new, SetDisplayObjectiveSerializer_v291.INSTANCE, 107, PacketRecipient.CLIENT)
            .registerPacket(SetScorePacket::new, SetScoreSerializer_v291.INSTANCE, 108, PacketRecipient.CLIENT)
            .registerPacket(LabTablePacket::new, LabTableSerializer_v291.INSTANCE, 109, PacketRecipient.BOTH)
            .registerPacket(UpdateBlockSyncedPacket::new, UpdateBlockSyncedSerializer_v291.INSTANCE, 110, PacketRecipient.CLIENT)
            .registerPacket(MoveActorDeltaPacket::new, MoveActorDeltaSerializer_v291.INSTANCE, 111, PacketRecipient.CLIENT)
            .registerPacket(SetScoreboardIdentityPacket::new, SetScoreboardIdentitySerializer_v291.INSTANCE, 112, PacketRecipient.CLIENT)
            .registerPacket(SetLocalPlayerAsInitializedPacket::new, SetLocalPlayerAsInitializedSerializer_v291.INSTANCE, 113, PacketRecipient.SERVER)
            .registerPacket(UpdateSoftEnumPacket::new, UpdateSoftEnumSerializer_v291.INSTANCE, 114, PacketRecipient.CLIENT)
            .registerPacket(NetworkStackLatencyPacket::new, NetworkStackLatencySerializer_v291.INSTANCE, 115, PacketRecipient.BOTH)
            .registerPacket(ScriptCustomEventPacket::new, ScriptCustomEventSerializer_v291.INSTANCE, 117, PacketRecipient.BOTH)
            .build();
}
